#!/usr/bin/env python3

import media_control
import sys

args = media_control.parse_arguments()

media_control.init()

WM = media_control.WatchingMedia()
CH = media_control.ConfigHandler()

if args.show:
    CH.show()

elif args.series_dir:
    new_series_dir = args.series_dir
    CH.update_series_dir(new_series_dir)

elif args.set:
    config_value = args.set
    CH.update_conf(config_value)

else:
    CH.check_if_inited()

if len(sys.argv) == 1:
    latest_episode = WM.play_next_episode()
    CH.update_previous_episode(latest_episode)

elif args.previous:
    WM.play_previous_episode()

CH.write()
